apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: your_dockerhub_username/myapp:latest
        ports:
        - containerPort: 80
        env:
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: myapp-config
              key: welcome_message
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: password
